[pyprland]
plugins = [
    "scratchpads",
    "monitors"
]

[scratchpads.term]
# command = "alacritty --class dropdown -e zsh -c \"tmux new-session -A -s default\""
command = "foot -a dropdown zsh -c \"tmux new-session -A -s default\""
class = "dropdown"
animation = "fromTop"
margin = 50
# unfocus = "hide"
lazy = true
match_by = "class"
size = "75% 80%"
# max_size = "1920px 100%"

[scratchpads.kitty]
command = "kitty --class dropdown-kitty --session ~/.config/kitty/sessions/default.conf"
class = "dropdown-kitty"
animation = "fromTop"
margin = 50
lazy = true
match_by = "class"
size = "75% 80%"

[monitors]
unknown = "wlrlui"

[monitors.placement."HP"]
leftOf = "eDP-1"
