version = "1.2.0"

[class]
"(?i)brave-browser" = "<span>󰖟</span>"
chromium = ""
".*transmission.*" = ""
libreoffice-startcenter = ""
"(?i)floorp" = "<span color='green'>󰖟</span>"
foot = "󰆍"
"(?i)slack" = "󰒱"
virt-manager = ""
libreoffice-impress = ""
swappy = ""
libreoffice-calc = ""
dropdown = "<span color='yellow'>󰆍</span>"
zoom = ""
"(?i)emacs" = "<span color='purple'></span>"
"(?i)zathura" = ""
DEFAULT = ""
libreoffice-writer = ""
"(?i)waydroid.*" = "droid"
pavucontrol = ""
"(?i)firefox" = "<span color='orange'> </span>"

[class_active]

[initial_class]

[initial_class_active]

[workspaces_name]

[title_in_class."(?i)foot"]
"emerge: (.+?/.+?)-.*" = "{match1}"

[title_in_class."(brave-browser|firefox|chrom.*|floorp)"]
"(?i)github" = "<span color='grey'></span>"
"(?i)youtube" = ""

[title_in_class_active."(brave-browser|firefox|chrom.*|floorp)"]
"(?i)youtube" = "<span color='red'></span>"
"(?i)github" = ""

[title_in_initial_class]

[title_in_initial_class_active]

[initial_title_in_class]

[initial_title_in_class_active]

[initial_title_in_initial_class]

[initial_title_in_initial_class_active]

[exclude]
"[Ss]team" = "^(Friends List.*)?$"
aProgram = "^$"
"(?i)TestApp" = ""
"" = "^$"
"(?i)fcitx" = ".*"

[format]
dedup = true
dedup_inactive_fullscreen = false
delim = " "
workspace = "<b><span>{id}:</span></b>{delim}{clients}"
workspace_empty = "<b><span color='grey'>{id}:</span></b>{delim}{clients}"
client = "{icon}"
client_fullscreen = "[{icon}]{delim}"
client_active = "<span>{icon}</span>"
client_dup = "{icon}{counter_sup}{delim}"
client_dup_active = "*{icon}*{delim}{icon}{counter_unfocused_sup}"
client_dup_fullscreen = "[{icon}]{delim}{icon}{counter_unfocused_sup}"
