# scratchpads
# bind = $super, y, exec, ~/.local/bin/pypr toggle term
bind = $super, t, exec, pypr toggle kitty
windowrule = float, class:^(dropdown)$
windowrule = workspace special:scratch_term silent, class:^(dropdown)$
windowrule = size 75% 60%, class:^(dropdown)$
windowrule = move 12% -200%, class:^(dropdown)$

windowrule = float, class:^(dropdown-kitty)$
windowrule = workspace special:scratch_kitty silent, class:^(dropdown-kitty)$
windowrule = size 75% 60%, class:^(dropdown-kitty)$
windowrule = move 12% -200%, class:^(dropdown-kitty)$
windowrule = opacity 0.9 0.8, class:^(dropdown-kitty)$

windowrule = float, class:^(org.kde.polkit-kde-authentication-agent-1)$
windowrule = float, class:^(pavucontrol)$
windowrule = float, class:^(nm-connection-editor)$
windowrule = float, class:^(blueman-manager)$
# windowrule = float, class:^([Zz]oom)$
windowrule = float, class:^(Slack)$
windowrule = float, class:^(rofi)$
windowrule = float, class:^(pulseUI)$

windowrule = center, class:^(pavucontrol)$

windowrule = opacity 0.95 0.8, class:^([Rr]ofi)$
windowrule = opacity 0.95 0.8, class:^(firefox)$
windowrule = opacity 0.97 0.8, class:^([Ee]macs)$
windowrule = opacity 0.9 0.8, class:^(dropdown)$

# idle inhibit
windowrule = idleinhibit focus, class:^(mpv|[Zz]oom|rpcs3|.*yuzu)$
windowrule = idleinhibit focus, class:^(firefox|floorp)$, title:^(.*YouTube.*)$
windowrule = idleinhibit focus, title:^([fF]oot)$

# force focus on some floating window
windowrule = stayfocused, class:^(org.kde.polkit-kde-authentication-agent-1)$
windowrule = dimaround, class:^(org.kde.polkit-kde-authentication-agent-1)$
windowrule = stayfocused, class:^(gcr-prompter)$
windowrule = dimaround, class:^(gcr-prompter)$
windowrule = stayfocused, class:^(Rofi)$
