# scratchpads
bind = $super, t, exec, pypr toggle kitty
windowrule = float on, match:class ^(dropdown)$
windowrule = workspace special:scratch_term silent, match:class ^(dropdown)$
windowrule = size 75% 60%, match:class ^(dropdown)$
windowrule = move 12% -200%, match:class ^(dropdown)$

windowrule = float on, match:class ^(dropdown-kitty)$
windowrule = workspace special:scratch_kitty silent, match:class ^(dropdown-kitty)$
windowrule = size 75% 60%, match:class ^(dropdown-kitty)$
windowrule = move 12% -200%, match:class ^(dropdown-kitty)$
windowrule = opacity 0.9 0.8, match:class ^(dropdown-kitty)$

windowrule = float on, match:class ^(org.kde.polkit-kde-authentication-agent-1)$
windowrule = float on, match:class ^(pavucontrol)$
windowrule = float on, match:class ^(nm-connection-editor)$
windowrule = float on, match:class ^(blueman-manager)$
windowrule = float on, match:class ^([Zz]oom)$
windowrule = no_initial_focus on, match:class ^([Zz]oom)$, match:title ^(annotate_toolbar)$
windowrule = suppress_event activate activatefocus, match:class ^([Zz]oom)$, match:title ^(annotate_toolbar)$
windowrule = float on, match:class ^(Slack)$
windowrule = float on, match:class ^(rofi)$
windowrule = float on, match:class ^(PulseUI)$
windowrule = center on, match:class ^(PulseUI)$

windowrule = center on, match:class ^(pavucontrol)$

windowrule = opacity 0.95 0.8, match:class ^([Rr]ofi)$
windowrule = opacity 0.95 0.8, match:class ^(firefox)$
windowrule = opacity 0.97 0.8, match:class ^([Ee]macs)$
windowrule = opacity 0.9 0.8, match:class ^(dropdown)$

# idle inhibit
windowrule = idle_inhibit focus, match:class ^(mpv|[Zz]oom|rpcs3|.*yuzu)$
windowrule = idle_inhibit focus, match:class ^(firefox|floorp)$, match:title ^(.*YouTube.*)$
windowrule = idle_inhibit focus, match:title ^([fF]oot)$

# force focus on some floating window
windowrule = stay_focused on, match:class ^(org.kde.polkit-kde-authentication-agent-1)$
windowrule = dim_around on, match:class ^(org.kde.polkit-kde-authentication-agent-1)$
windowrule = stay_focused on, match:class ^(gcr-prompter)$
windowrule = dim_around on, match:class ^(gcr-prompter)$
windowrule = stay_focused on, match:class ^(Rofi)$
